"use client";

import React, { useState, useEffect } from "react";

const Features = () => {
  const [currentImg, setCurrentImg] = useState(0);

  const mockupImages = [
    "https://artart-uploads.s3.amazonaws.com/2023/04/2023-04-19-ai-kr-image5-939763-4Kp20eZR.webp",
    "https://www.theartist.me/wp-content/uploads/2023/10/future-of-art.jpg",
    "https://imageio.forbes.com/specials-images/imageserve/6200b0dddcf32d3be937fa84/0x0.jpg?format=jpg&height=900&width=1600&fit=bounds",
    "https://static.wixstatic.com/media/a0ce48_d1362afd674b4227b213ec624d953d34~mv2.png/v1/fill/w_568,h_318,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/a0ce48_d1362afd674b4227b213ec624d953d34~mv2.png",
    "https://cdn.prod.website-files.com/65a1b21a5fcbab501a6f2d5c/67a79310d23b701cc11a76de_simona.webp",
    "https://img.pikbest.com/backgrounds/20250217/the-future-technology-of-robots-combined-with-the-human-brain-and-existence_11533094.jpg!w700wp",
    "https://dionhinchcliffe.com/wp-content/uploads/2024/02/dallc2b7e-2024-02-14-21.34.47-generate-a-visual-that-beautifully-merges-a-lifelike-organic-and-pastoral-view-with-clear-depictions-of-the-evolving-user-interface-trends-ensuring-e.webp?w=584",
    "https://res.cloudinary.com/jerrick/image/upload/c_scale,f_jpg,q_auto/67cfee68070b31001da74d17.webp",
    "https://miro.medium.com/v2/resize:fit:1400/1*LD-tL8U221WuVj6sS-vgaA.png",
    "https://aba.co.uk/publications/the-spirit-of-christmas-future-technology-human-interaction-or-both/feature.jpg"
  ];


  useEffect(() => {
    const timer = setInterval(() => {
      setCurrentImg((prev) => (prev + 1) % mockupImages.length);
    }, 3000);
    return () => clearInterval(timer);
  }, []);

  const featureList = [
    {
      id: 1,
      title: "Neural Search Engine",
      description: "Locate assets instantly with our AI-powered neural search. Context-aware filtering.",
      icon: (
        <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
        </svg>
      ),
      glow: "group-hover:shadow-[0_0_20px_rgba(34,211,238,0.5)]",
    },
    {
      id: 2,
      title: "Quantum Bulk Logic",
      description: "Batch process thousands of assets simultaneously using distributed architecture.",
      icon: (
        <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 6h16M4 10h16M4 14h16M4 18h16" />
        </svg>
      ),
      glow: "group-hover:shadow-[0_0_20px_rgba(59,130,246,0.5)]",
    },
    {
      id: 3,
      title: "Predictive Analytics",
      description: "Automated inventory forecasting generated by real-time data streams.",
      icon: (
        <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
      ),
      glow: "group-hover:shadow-[0_0_20px_rgba(168,85,247,0.5)]",
    },
    {
      id: 4,
      title: "Zero-Trust Security",
      description: "Military-grade encryption with granular access to safeguard sensitive data.",
      icon: (
        <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
        </svg>
      ),
      glow: "group-hover:shadow-[0_0_20px_rgba(236,72,153,0.5)]",
    },
  ];

  return (
    <section className="relative py-32 bg-[#050505] overflow-hidden">
      <div className="absolute top-0 -left-1/4 w-1/2 h-1/2 bg-cyan-500/10 blur-[120px] rounded-full"></div>
      <div className="absolute bottom-0 -right-1/4 w-1/2 h-1/2 bg-blue-600/10 blur-[120px] rounded-full"></div>

      <div className="max-w-7xl mx-auto px-6 relative z-10">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-20 items-center">
          
          <div className="relative group">
            <div className="absolute -inset-1 bg-gradient-to-r from-cyan-500 to-blue-600 rounded-[2.5rem] blur opacity-25 group-hover:opacity-50 transition duration-1000"></div>
            
            <div className="relative rounded-[2rem] overflow-hidden border border-white/10 bg-[#0a0a0a] shadow-2xl">
              <div className="h-10 bg-white/5 border-b border-white/10 flex items-center px-6 gap-2">
                <div className="flex gap-1.5">
                  <div className="w-2.5 h-2.5 rounded-full bg-red-500/50"></div>
                  <div className="w-2.5 h-2.5 rounded-full bg-yellow-500/50"></div>
                  <div className="w-2.5 h-2.5 rounded-full bg-green-500/50"></div>
                </div>
                <div className="mx-auto w-32 h-2 bg-white/10 rounded-full"></div>
              </div>

    
              <div className="relative aspect-[4/3] overflow-hidden">
                {mockupImages.map((img, index) => (
                  <img
                    key={index}
                    src={img}
                    alt={`Tech Interface ${index + 1}`}
                    className={`absolute inset-0 w-full h-full object-cover transition-all duration-1000 ease-in-out ${
                      index === currentImg ? "opacity-100 scale-100" : "opacity-0 scale-110"
                    }`}
                  />
                ))}
                <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] opacity-20 pointer-events-none"></div>
                <div className="absolute inset-0 bg-gradient-to-t from-[#0a0a0a] via-transparent to-transparent"></div>
              </div>
            </div>

            {/* Floating Info Card */}
            <div className="absolute -bottom-10 -right-10 hidden md:block w-64 p-6 rounded-2xl border border-white/10 bg-white/5 backdrop-blur-xl shadow-xl animate-bounce-slow">
              <div className="flex items-center gap-4 mb-3">
                <div className="w-3 h-3 rounded-full bg-cyan-400 animate-pulse"></div>
                <div className="text-[10px] text-cyan-400 font-black uppercase tracking-widest">
                   Syncings Layer: 0{currentImg + 1}
                </div>
              </div>
              <div className="h-1 w-full bg-white/10 rounded-full mb-2">
                <div 
                  className="h-full bg-cyan-400 rounded-full transition-all duration-500" 
                  style={{ width: `${(currentImg + 1) * 10}%` }}
                ></div>
              </div>
              <p className="text-[9px] text-gray-400 italic font-medium">Updating global data matrix...</p>
            </div>
          </div>

          <div>
            <div className="mb-16">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-cyan-500/30 bg-cyan-500/5 mb-6">
                <span className="w-2 h-2 rounded-full bg-cyan-400 animate-pulse"></span>
                <span className="text-[10px] font-black uppercase tracking-[0.2em] text-cyan-400">Core Protocol</span>
              </div>
              <h2 className="text-3xl md:text-5xl font-black text-white leading-[1.1] tracking-tighter mb-8">
                Master Your <span className="bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent italic">Digital Galaxy</span>
              </h2>
              <p className="text-gray-400 text-lg leading-relaxed font-medium">
                TechVibe bypasses standard limitations. Our architecture is built for the pioneers of the next industrial era.
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {featureList.map((feature) => (
                <div 
                  key={feature.id} 
                  className="group relative p-6 rounded-2xl border border-white/5 bg-white/[0.02] hover:bg-white/[0.05] transition-all duration-500"
                >
                  <div className={`w-12 h-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mb-6 transition-all duration-500 ${feature.glow}`}>
                    <div className="text-cyan-400 transition-transform duration-500 group-hover:scale-110">
                      {feature.icon}
                    </div>
                  </div>
                  <h3 className="text-lg font-bold text-white mb-3 tracking-tight group-hover:text-cyan-400 transition-colors">
                    {feature.title}
                  </h3>
                  <p className="text-sm text-gray-500 leading-relaxed font-medium">
                    {feature.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      <style jsx>{`
        @keyframes bounce-slow {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-15px); }
        }
        .animate-bounce-slow {
          animation: bounce-slow 4s ease-in-out infinite;
        }
      `}</style>
    </section>
  );
};

export default Features;